### ISSUE TITLE
Trocar 'back-button' em page-detalhe por um 'close icon' posicionado à direita

### ISSUE THREAD

**Issue by AndreaInfUFSM** [ERAD2018/ERAD2018.github.io#1]
O back-button à esquerda é menos ergonômico por geralmente exigir uso da mão esquerda. 
Um botão para fechar a página de detalhes, posicionado à direita, permite que as ações mais comuns sejam feitas só com a mão direita.

**Comment by Felipe-Marin** [comment]
Como bônus foi adicionado a opção de voltar dentro das página do app usando o botão do navegador ou botão "físico" do Android.
