### ISSUE TITLE
Horários das sessões

### ISSUE THREAD

**Issue by schnorr** [ERAD2018/ERAD2018.github.io#12]
O horário da sessão é definido a partir do HoraInicio e HoraFim do primeiro trabalho da sessão. Faria mais sentido se fosse do min(HoraInicio) até o max(HoraFim) dos trabalhos daquela sessão.

**Comment by schnorr** [comment]
Só confirmando que 6f8e599 resolve o problema.

**Comment by schnorr** [comment]
Parece que o problema voltou.

**Comment by Felipe-Marin** [comment]
@schnorr Não consegui reproduzir o problema na versão atual do aplicativo.
