### ISSUE TITLE
Código da App é ilegível no Github/Ferramentas de Diff

### ISSUE THREAD

**Issue by schnorr** [ERAD2018/ERAD2018.github.io#13]
Oi, só deixar registrado que não existem quebras de linha no código fonte da App aqui no Github. Isso é uma prática indesejável pois não permite avaliar claramente o diff de um commit, seja pela interface web do github, seja com qualquer ferramenta local. Talvez fosse interessante adicionar as quebras de linha no fonte em lugares apropriados.

**Comment by Felipe-Marin** [comment]
Esse repositório tem a 'production build' gerada pelo ionic, com o js e CSS minificados, que fica disponível no erad2018.github.io, o código está no repositório: https://github.com/ERAD2018/PWA-ERAD
